# This file was generated by GoReleaser. DO NOT EDIT.
cask "clavesa" do
  version "1.1.4"

  on_macos do
    on_intel do
      sha256 "5f0a88314ba3f712fcf04066b7ec8c6da0e7d87660ea110a86cc8bc93cc756ee"
      url "https://github.com/vesahyp/clavesa/releases/download/v#{version}/clavesa_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "e4811c3f9afa6c0d02b42d1864b7992b6a30546a636f88f3499aa88aad91fb10"
      url "https://github.com/vesahyp/clavesa/releases/download/v#{version}/clavesa_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "9fc89bb1e72cb55ce315c97ddc03a9725f9d2f9de81e811cf5eb471fd37e4c7f"
      url "https://github.com/vesahyp/clavesa/releases/download/v#{version}/clavesa_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "08871b7eac0026620d6acf2beb06a528204afa37deefaa29e00e498cadf91579"
      url "https://github.com/vesahyp/clavesa/releases/download/v#{version}/clavesa_#{version}_linux_arm64.tar.gz"
    end
  end

  name "clavesa"
  desc "Visual ETL tool where pipelines are Terraform"
  homepage "https://github.com/vesahyp/clavesa"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "clavesa"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/clavesa"]
    end
  end

  # No zap stanza required

end
