# This file was generated by GoReleaser. DO NOT EDIT.
cask "clavesa" do
  version "2.21.0"

  on_macos do
    on_arm do
      sha256 "1beea4744a58306c05528d05d89dc2b0fe7999dbdd80c652f64915e7c068e029"
      url "https://github.com/vesahyp/clavesa/releases/download/v#{version}/clavesa_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "59db24a198102bf6f6e13dd753bf31fe2bf4ee3f0b66f4c31ec882614757be32"
      url "https://github.com/vesahyp/clavesa/releases/download/v#{version}/clavesa_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "0f9bca603822557cb269f92055831107c556c94a2ad620a25f92c5f13b66e555"
      url "https://github.com/vesahyp/clavesa/releases/download/v#{version}/clavesa_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "ac28e64c95da2268ee765a4e536b4429d5a128f867b3f21e7c933a182ba06c94"
      url "https://github.com/vesahyp/clavesa/releases/download/v#{version}/clavesa_#{version}_linux_amd64.tar.gz"
    end
  end

  name "clavesa"
  desc "Visual ETL tool where pipelines are Terraform"
  homepage "https://github.com/vesahyp/clavesa"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "clavesa"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/clavesa"]
    end
  end

  # No zap stanza required
end
