# This file was generated by GoReleaser. DO NOT EDIT.
cask "clavesa" do
  version "2.7.3"

  on_macos do
    on_intel do
      sha256 "c8f93a7421f51c2eb94911f749c29f7d1b6a9d8d1cda273926253f167852b68e"
      url "https://github.com/vesahyp/clavesa/releases/download/v#{version}/clavesa_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "52a770f8d98d77e80c85b69b5236ee0852e7a35f748b5634e0fbd304de4f717b"
      url "https://github.com/vesahyp/clavesa/releases/download/v#{version}/clavesa_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "81c64cc2fcb97e7f52090317b7e52a2fa63a2aa05879e6d86b57ac093b92c903"
      url "https://github.com/vesahyp/clavesa/releases/download/v#{version}/clavesa_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "1e1d2c1de9403b5445a142f511ede6d602dbbcde75ccd192aac501fc2f36fbf7"
      url "https://github.com/vesahyp/clavesa/releases/download/v#{version}/clavesa_#{version}_linux_arm64.tar.gz"
    end
  end

  name "clavesa"
  desc "Visual ETL tool where pipelines are Terraform"
  homepage "https://github.com/vesahyp/clavesa"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "clavesa"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/clavesa"]
    end
  end

  # No zap stanza required

end
