# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Clavesa < Formula
  desc "Visual ETL tool where pipelines are Terraform"
  homepage "https://github.com/vesahyp/clavesa"
  version "1.0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/vesahyp/clavesa/releases/download/v1.0.1/clavesa_1.0.1_darwin_amd64.tar.gz"
      sha256 "8a46060492303f4ca40d2cbe2d0a83e0257f89132d1fe83792948585f60d29c4"

      define_method(:install) do
        bin.install "clavesa"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/vesahyp/clavesa/releases/download/v1.0.1/clavesa_1.0.1_darwin_arm64.tar.gz"
      sha256 "c88f6fb8a21c122c7031d21e39615f01f9dba92bb2288cc077bacc1335acdd46"

      define_method(:install) do
        bin.install "clavesa"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/vesahyp/clavesa/releases/download/v1.0.1/clavesa_1.0.1_linux_amd64.tar.gz"
      sha256 "90f35af19e6eaa41cc75cc045e33192e10953242031c80f6697c5fada374545c"
      define_method(:install) do
        bin.install "clavesa"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/vesahyp/clavesa/releases/download/v1.0.1/clavesa_1.0.1_linux_arm64.tar.gz"
      sha256 "21cd18c2db8167d4573c1b5655519f9994819f8642bd2301b0f7eab783a4987f"
      define_method(:install) do
        bin.install "clavesa"
      end
    end
  end

  test do
    system "#{bin}/clavesa", "version"
  end
end
